.PHONY: build test lint-arch lint verify setup-env start-server teardown-env api-doc check-db api-test check-conventions

build:
	cd star-park/pc-admin && npm run build

test:
	@echo "No tests configured yet"

# ====== Web 应用条件目标 ======

api-doc: ## 生成/更新 API 接口文档 (docs/api.md)
	@if [ -f scripts/generate-api-doc.sh ]; then \
		bash scripts/generate-api-doc.sh; \
	else \
		echo "跳过: 非 Web 应用项目"; \
	fi

check-db: ## DDL/Entity 一致性检查
	@if [ -f scripts/check-db-consistency.sh ]; then \
		bash scripts/check-db-consistency.sh; \
	else \
		echo "跳过: 无数据库依赖"; \
	fi

api-test: ## 运行 API 接口测试
	@if [ -f scripts/run-api-tests.sh ]; then \
		bash scripts/run-api-tests.sh; \
	else \
		echo "跳过: 非 Web 应用项目"; \
	fi

check-conventions: ## 编码规范检查
	@if [ -f scripts/code-review-check.sh ]; then \
		bash scripts/code-review-check.sh; \
	else \
		echo "跳过: 未配置编码规范检查"; \
	fi

# --- FIXED TARGETS (do NOT modify — generated by scaffold) ---

lint-arch:
	@echo "Checking architecture constraints..."
	@for f in scripts/lint-deps.*; do \
		case "$$f" in *.sh) bash "$$f" ;; *.py) python3 "$$f" ;; *.go) go run "$$f" ;; esac; \
	done
	@for f in scripts/lint-quality.*; do \
		case "$$f" in *.sh) bash "$$f" ;; *.py) python3 "$$f" ;; *.go) go run "$$f" ;; esac; \
	done
	@echo "✓ Architecture checks passed"

lint: lint-arch
	@echo "✓ All lint checks passed"

verify:
	@echo "Running end-to-end verification..."
	@for f in scripts/verify/*.sh; do \
		echo "→ $$f"; \
		bash "$$f" || exit 1; \
	done
	@echo "✓ All verification scenarios passed"

setup-env:
	./harness/scripts/setup-env.sh

start-server:
	./harness/scripts/start-server.sh

teardown-env:
	./harness/scripts/teardown-env.sh
